version: 2

models:
  - name: unanswered_questions_facts
    description: "Fact table for unanswered questions"
    tests:
      - not_null:
          column_name: question_id
      - not_null:
          column_name: creation_date
      - not_null:
          column_name: user_sk

  - name: users_dimension
    description: "Dimension table for users"
    tests:
      - not_null:
          column_name: user_id
      - not_null:
          column_name: reputation
      - not_null:
          column_name: creation_date

  - name: tags_dimension
    description: "Dimension table for tags"
    tests:
      - not_null:
          column_name: tag_name

  - name: date_dimension
    description: "Dimension table for date"
    tests:
      - not_null:
          column_name: calendar_date
